import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useNavigate, useParams } from "react-router-dom";
import ReactMarkdown from "react-markdown";
import { api, del, postJson } from "@/api/client";
import { Button } from "@/components/ui/Button";
import type { Article } from "@/lib/types";

export function ReadPage() {
  const qc=useQueryClient(); const [url,setUrl]=useState(""); const [lang,setLang]=useState("German"); const [level,setLevel]=useState("B1");
  const { data:articles=[] }=useQuery({queryKey:["articles"],queryFn:()=>api<Article[]>("/api/articles"),refetchInterval:(q)=>q.state.data?.some(a=>["fetching","translating"].includes(a.status))?2000:false});
  const create=useMutation({mutationFn:()=>postJson<{articleId:string}>("/api/articles",{url,targetLanguage:lang,cefrLevel:level}),onSuccess:()=>{setUrl("");qc.invalidateQueries({queryKey:["articles"]});}});
  return <div className="mx-auto max-w-3xl"><h1 className="mb-6 text-2xl font-black">Read Articles</h1><div className="mb-6 rounded-2xl border-2 border-lingo-border bg-white p-4"><h2 className="mb-3 font-black">Translate a new article</h2><div className="grid gap-2 md:grid-cols-[1fr_auto_auto_auto]"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://..." className="rounded-xl border-2 border-lingo-border px-3 py-2"/><select value={lang} onChange={e=>setLang(e.target.value)} className="rounded-xl border-2 border-lingo-border bg-white px-3 py-2"><option>German</option><option>Spanish</option><option>French</option><option>Italian</option><option>Portuguese</option></select><select value={level} onChange={e=>setLevel(e.target.value)} className="rounded-xl border-2 border-lingo-border bg-white px-3 py-2">{["A1","A2","B1","B2","C1","C2"].map(l=><option key={l}>{l}</option>)}</select><Button disabled={!url.trim()} loading={create.isPending} onClick={()=>create.mutate()}>Translate</Button></div></div><div className="space-y-3">{articles.map(a=><Link key={a.id} to={`/read/${a.id}`} className="block rounded-2xl border-2 border-lingo-border bg-white p-4 hover:border-lingo-blue"><div className="flex items-start justify-between"><div><h3 className="font-black">{a.title || "Untitled"}</h3><p className="text-sm text-lingo-text-light">{domain(a.sourceUrl)} · {a.targetLanguage} · {a.cefrLevel}</p></div><Status article={a}/></div>{["fetching","translating"].includes(a.status)&&<div className="mt-3 h-2 overflow-hidden rounded-full bg-lingo-gray"><div className="h-full bg-lingo-blue" style={{width:`${a.totalParagraphs? a.translationProgress/a.totalParagraphs*100: 15}%`}}/></div>}</Link>)}</div>{!articles.length&&<p className="rounded-2xl border-2 border-dashed border-lingo-border p-8 text-center text-lingo-text-light">No articles yet.</p>}</div>;
}

export function ArticlePage() {
  const { id }=useParams(); const nav=useNavigate(); const qc=useQueryClient();
  const { data:article }=useQuery({queryKey:["article",id],queryFn:()=>api<Article>(`/api/articles/${id}`),refetchInterval:(q)=>q.state.data&&!["completed","failed"].includes(q.state.data.status)?2000:false});
  const remove=useMutation({mutationFn:()=>del(`/api/articles/${id}`),onSuccess:()=>{qc.invalidateQueries({queryKey:["articles"]});nav("/read")}});
  const audio=useMutation({mutationFn:()=>postJson(`/api/articles/${id}/audio`,{}),onSuccess:()=>qc.invalidateQueries({queryKey:["article",id]})});
  const blocks=useMemo(()=>{try{return article?.translatedContent?JSON.parse(article.translatedContent):[]}catch{return[]}},[article?.translatedContent]);
  if(!article)return <p>Loading article...</p>;
  return <div className="mx-auto max-w-3xl"><button className="mb-4 font-bold text-lingo-text-light" onClick={()=>nav("/read")}>← All articles</button><div className="mb-6 flex items-start justify-between gap-3"><div><h1 className="text-2xl font-black">{article.title||"Untitled"}</h1><p className="mt-1 text-sm text-lingo-text-light">{domain(article.sourceUrl)} · {article.targetLanguage} · {article.cefrLevel}</p></div><div className="flex gap-2"><Button variant="secondary" onClick={()=>audio.mutate()} loading={audio.isPending}>Audio</Button><Button variant="danger" onClick={()=>confirm("Delete article?")&&remove.mutate()}>Delete</Button></div></div>{article.status!=="completed"?<div className="rounded-2xl border-2 border-lingo-border bg-white p-8 text-center"><Status article={article}/><p className="mt-3 text-lingo-text-light">{article.status} {article.totalParagraphs?`${article.translationProgress}/${article.totalParagraphs}`:""}</p>{article.errorMessage&&<p className="mt-2 text-lingo-red">{article.errorMessage}</p>}</div>:<div className="space-y-4">{blocks.map((b:any,i:number)=><div key={i} className="rounded-2xl border-2 border-lingo-border bg-white p-5"><div className="prose max-w-none"><ReactMarkdown>{b.translated}</ReactMarkdown></div><details className="mt-3 text-sm text-lingo-text-light"><summary className="cursor-pointer font-bold">Original / bridge</summary><p className="mt-2">{b.original}</p>{b.bridge&&<p className="mt-2 italic">{b.bridge}</p>}</details></div>)}</div>}</div>;
}

function Status({article}:{article:Article}){if(article.status==="completed")return <span className="rounded-full bg-lingo-green/10 px-3 py-1 text-xs font-black text-lingo-green">Complete</span>; if(article.status==="failed")return <span className="rounded-full bg-lingo-red/10 px-3 py-1 text-xs font-black text-lingo-red">Failed</span>; return <span className="rounded-full bg-lingo-blue/10 px-3 py-1 text-xs font-black text-lingo-blue">Working…</span>}
function domain(url:string){try{return new URL(url).hostname.replace("www.","")}catch{return url}}
